### ISSUE TITLE
Saying "Athena" triggers this error.

### ISSUE THREAD

**Issue by ghost** [athena-voice/athena-voice-client#54]
~ Hey there, Bro!
    
~ Try asking:
  - "Athena (double beep) what's the weather like in DFW?"
  - "Athena (double beep) what is the capital of Tanzania?"
  - "Athena (double beep) open facebook.com"
     
ALSA lib pcm_dmix.c:1041:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1041:(snd_pcm_dmix_open) unable to open slave
    
~ Waiting to be woken up... 
    
~ (runtime error)
    
~ Something went wrong. Would you like to see the error message?
Unexpected error loading library libavbin.so.10: libavbin.so.10: wrong ELF class: ELFCLASS64
    
~ Unknown Google TTS issue: libavbin.so.10: wrong ELF class: ELFCLASS64
Continue? (Y/N) y
    
~ Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/athena/brain.py", line 222, in run
    text = stt.active_listen()
  File "/usr/local/lib/python3.5/dist-packages/athena/stt.py", line 62, in active_listen
    with speech_recognition.Microphone() as src:
  File "/usr/local/lib/python3.5/dist-packages/speech_recognition/\_\_init\_\_.py", line 79, in \_\_init\_\_
    self.pyaudio_module = self.get_pyaudio()
  File "/usr/local/lib/python3.5/dist-packages/speech_recognition/\_\_init\__.py", line 113, in get_pyaudio
    raise AttributeError("PyAudio 0.2.9 or later is required (found version {})".format(pyaudio.\_\_version\_\_))
AttributeError: PyAudio 0.2.9 or later is required (found version 0.2.8)

(END LOG)

Fresh install of Ubuntu GNOME 16.10, thinkpad x201 tablet, intel core vpro i7.

Followed instuctions from [here](https://heyathena.com/docs/intro/install.html), under section "Ubuntu/Raspberry Pi/Linux".

Help?

(P.S: Github wont let me put the log into a code thing, sorry)

**Comment by ghost** [comment]
I fixed this by installing the latest PyAudio, by downloading it from pypi's website in tar.gz format and executing its setup.py file with `python3 setup.py install`, and installing the 32 bit version of avbin.
