### ISSUE TITLE
OSError: [Errno -9997] Invalid sample rate

### ISSUE THREAD

**Issue by Mofiqul** [athena-voice/athena-voice-client#57]
I am getting this error on 
Ubuntu-16.04 64 bit
Error Message:
```
~ Hey there, Mofi!

~ Try asking:
  - "Athena (double beep) what's the weather like in DFW?"
  - "Athena (double beep) what is the capital of Tanzania?"
  - "Athena (double beep) open facebook.com"

Home directory not accessible: Permission denied
ALSA lib pcm_dsnoop.c:606:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
Home directory not accessible: Permission denied
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Home directory not accessible: Permission denied
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_dsnoop.c:606:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/athena/brain.py", line 221, in run
    stt.listen_keyword()
  File "/usr/local/lib/python3.5/dist-packages/athena/stt.py", line 39, in listen_keyword
    input=True, frames_per_buffer=1024)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9997] Invalid sample rate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/athena/__main__.py", line 14, in <module>
    brain.inst.run()
  File "/usr/local/lib/python3.5/dist-packages/athena/brain.py", line 237, in run
    raise Exception
Exception
```

**Comment by dimitrisTim** [comment]
Same error on a clean image of Stretch in Raspberry Pi 3.
