### ISSUE TITLE
RuntimeError: new_Decoder returned -1

### ISSUE THREAD

**Issue by JGabrielGruber** [athena-voice/athena-voice-client#58]
~ Try asking:
  - "Athena (double beep) what's the weather like in DFW?"
  - "Athena (double beep) what is the capital of Tanzania?"
  - "Athena (double beep) open facebook.com"

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/HeyAthena-1.3.2-py2.7.egg/athena/__main__.py", line 12, in <module>
    brain.init()
  File "/usr/local/lib/python2.7/dist-packages/HeyAthena-1.3.2-py2.7.egg/athena/brain.py", line 24, in init
    inst = Brain()
  File "/usr/local/lib/python2.7/dist-packages/HeyAthena-1.3.2-py2.7.egg/athena/brain.py", line 53, in __init__
    stt.init()
  File "/usr/local/lib/python2.7/dist-packages/HeyAthena-1.3.2-py2.7.egg/athena/stt.py", line 44, in init
    decoder = Decoder(config)
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx/pocketsphinx.py", line 277, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1

**Comment by shepnathand** [comment]
try:
`sudo chown -R username:usergroup /usr/local/lib/python2.7/dist-packages/HeyAthena-1.3.2-py2.7.egg/athena/`
and
`sudo chmod -R 0777 /usr/local/lib/python2.7/dist-packages/HeyAthena-1.3.2-py2.7.egg/athena/`
